### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by favoyang** [dotBunny/GDX#14]
https://openupm.com/packages/com.dotbunny.gdx/?subPage=pipelines

Git tag: v1.1.1
Expected version: 1.1.1
Actually version: 1.1.0

To fix:
- bump version of package.json
- re-tag v1.1.1

**Comment by reapazor** [comment]
This one 100% on me, i didn't bump the package version when i pushed the button. Now, there are versions ahead of this, feel like it might be useful to just kill that release version.

**Comment by reapazor** [comment]
I've removed the 1.1.1 release, will kill tag.

**Comment by favoyang** [comment]
Looks good. Thanks for fixing it.
